import Head from 'next/head'
import Link from 'next/link'
import React from 'react'

const Layout = ( {children, title}) => {
  return (
   <>
   <Head>
        <title>{title ?title= ` - Solace`: 'Solace'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
   <div  className='flex min-h-screen flex-col justify-between'  >
    

    <header>
    <nav className="flex h-12 items-center px-4 justify-between shadow-md">
            <Link href="/" className="text-lg font-bold">Shopping</Link>
            <div>

            <Link href="/" className="p-2">Cart</Link>
            <Link href="/" className="p-2">Login</Link>
            </div>
            </nav>
       

    </header>

    <main className="container m-auto mt-4 px-4"> {children} </main>

    <footer className="flex h-10 justify-center items-center shadow-inner">
          <p>Copyright © 2023 Sandeep</p>
        </footer>
   </div>
   </>
  )
}

export default Layout