import { Store } from '@/utils/Store'
import { useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'
import React, { useContext, useEffect, useState } from 'react'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
const Layout = ( {children, title}) => {

const {status, data:session}= useSession()

  const [cartItemsCount, setCartItemsCount]= useState(0)
  useEffect(()=>{

    setCartItemsCount(cart.cartItems.reduce((a,c)=>a+c.quantity,0))
  })
    const {state}= useContext(Store)
    const {cart}= state;
  return (
   <>
   <Head>
        <title>{title ?title= ` - Solace`: 'Solace'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer position='bottom-center' limit={1}/>
   
   <div  className='flex min-h-screen flex-col justify-between'  >
    

    <header>
    <nav className="flex h-12 items-center px-4 justify-between shadow-md">
            <Link href="/" className="text-lg font-bold">Shopping</Link>
            <div>

            <Link href="/cart" className="p-2">
                
                {cartItemsCount>0 &&(
                    <span className='ml-1 rounded-full bg-red-500 px-2 py-1 text-xs font-bold text-white'>
                        {cartItemsCount}
                    </span>
                )}Cart</Link>

          
              {status === 'loading'?(
                'Loading'
                ):
                session?.user ?(session.user.name
                  ):(
              
                <Link href='/login'>
                  Login
                </Link>
              )}
            
            </div>
            </nav>
       

    </header>

    <main className="container m-auto mt-4 px-4"> {children} </main>

    <footer className="flex h-10 justify-center items-center shadow-inner">
          <p>Copyright © 2023 Sandeep</p>
        </footer>
   </div>
   </>
  )
}

export default Layout